Restroom.create!(
                cleanliness,
                uniqueness,
                upkeep,
                toilet_paper_quality,
                toilet_paper_quality,
                amenities,
                accessibility,
                number_of_stalls,
                number_of_stalls,
                size,
                privacy,
                location,
                summary,
                overall_rating
                )